### ISSUE TITLE
Suggestion for router problem

### ISSUE THREAD

**Issue by supernovel** [vlidholt/device_simulator#4]
```
  /// The [builder] callback is passed two arguments, the [BuildContext] (as
  /// `context`) and a [Navigator] widget (as `child`).
 MaterialApp(
      title: 'DeviceSimulator demo',
      builder: (_, child) {
        return DeviceSimulator(
          brightness: Brightness.dark,
          enable: debugEnableDeviceSimulator,
          child: child,
        );
      },
```

**Comment by danydev** [comment]
@vlidholt This is a great solution to integrate your widget. Do you see downside? Otherwise we could just update the README with that and remove the Navigator limitation

**Comment by vlidholt** [comment]
Great suggestions! I've released a new version that includes a custom Navigator. That seems to be working, with the exception of breaking Hero animations. Seems like a fair trade off for now.
